### Task 1.1a

In [3]:
import numpy as np

xdata = []
ydata = []
#xdata.append([ Di(m), qoflux (kW/m^2), mdot (kg/s)])


xdata.append([0.008, 550, 0.06157])
xdata.append([0.008, 650, 0.07269])
xdata.append([0.008, 750, 0.08396])
xdata.append([0.008, 850, 0.09347])
xdata.append([0.008, 950, 0.10635])
xdata.append([0.008, 1050, 0.11521])
xdata.append([0.008, 1150, 0.1287])
xdata.append([0.008, 850, 0.09516])
xdata.append([0.008, 550, 0.04398])
xdata.append([0.008, 750, 0.05997])
xdata.append([0.008, 950, 0.07596])
xdata.append([0.008, 1050, 0.08343])
xdata.append([0.008, 1150, 0.0919])
xdata.append([0.008, 850, 0.06797])
xdata.append([0.008, 550, 0.0342])
xdata.append([0.008, 750, 0.04664])
xdata.append([0.008, 950, 0.05908])
xdata.append([0.008, 1150, 0.0715])
xdata.append([0.008, 850, 0.05286])
xdata.append([0.011, 550, 0.0846])
xdata.append([0.011, 750, 0.1154])
xdata.append([0.011, 950, 0.1462])
xdata.append([0.011, 1150, 0.177])
xdata.append([0.011, 850, 0.1308])
xdata.append([0.011, 550, 0.06047])
xdata.append([0.011, 750, 0.08246])
xdata.append([0.011, 950, 0.1044])
xdata.append([0.011, 1050, 0.1134])
xdata.append([0.011, 1150, 0.1264])
xdata.append([0.011, 850, 0.0934])
xdata.append([0.011, 550, 0.047])
xdata.append([0.011, 750, 0.06413])
xdata.append([0.011, 950, 0.08124])
xdata.append([0.011, 1150, 0.09834])
xdata.append([0.011, 850, 0.072691])
xdata.append([0.011, 700, 0.087196])
xdata.append([0.013, 550, 0.10005])
xdata.append([0.013, 750, 0.13644])
xdata.append([0.013, 950, 0.17282])
xdata.append([0.013, 1150, 0.2092])
xdata.append([0.013, 850, 0.15463])
xdata.append([0.013, 550, 0.07147])
xdata.append([0.013, 750, 0.09745])
xdata.append([0.013, 950, 0.12344])
xdata.append([0.013, 1050, 0.13302])
xdata.append([0.013, 1150, 0.1494])
xdata.append([0.013, 850, 0.11045])
xdata.append([0.013, 550, 0.05558])
xdata.append([0.013, 750, 0.0758])
xdata.append([0.013, 950, 0.09601])
xdata.append([0.013, 1150, 0.1162])
xdata.append([0.013, 850, 0.0859])

#ydata.append([ exit quality, max wall temperature (deg C)])

ydata.append([0.525, 306.7])
ydata.append([0.525, 298.5])
ydata.append([0.525, 294.5])
ydata.append([0.525, 290.2])
ydata.append([0.524, 286.9])
ydata.append([0.524, 284.1])
ydata.append([0.525, 281.7])
ydata.append([0.524, 290.3])
ydata.append([0.734, 307.9])
ydata.append([0.735, 295.5])
ydata.append([0.735, 287.8])
ydata.append([0.735, 285.0])
ydata.append([0.735, 282.5])
ydata.append([0.734, 291.3])
ydata.append([ 0.945, 308.6])
ydata.append([0.945, 296.2])
ydata.append([0.945, 288.5])
ydata.append([0.945, 283.1])
ydata.append([0.945, 291.9])
ydata.append([ 0.525, 328.0])
ydata.append([0.525, 311.2])
ydata.append([0.525, 300.8])
ydata.append([0.525, 293.6])
ydata.append([0.525, 305.5])
ydata.append([0.735, 329.6])
ydata.append([0.735, 312.6])
ydata.append([0.735, 302.0])
ydata.append([0.735, 299.4])
ydata.append([0.735, 294.8])
ydata.append([0.735, 306.8])
ydata.append([ 0.945, 330.7])
ydata.append([0.945, 313.6])
ydata.append([0.944, 302.9])
ydata.append([0.945, 295.6])
ydata.append([0.944, 307.7])
ydata.append([0.734, 324.7])
ydata.append([0.525, 342.2])
ydata.append([0.524,  322.3])
ydata.append([0.524, 310.0])
ydata.append([0.525, 301.6])
ydata.append([0.524, 315.5])
ydata.append([0.734, 344.1])
ydata.append([0.735, 324.0])
ydata.append([0.735, 311.5])
ydata.append([0.735, 306.3])
ydata.append([0.735, 302.9])
ydata.append([0.734, 317.1])
ydata.append([0.945, 345.3])
ydata.append([0.944, 325.1])
ydata.append([0.944, 312.5])
ydata.append([0.945, 303.9])
ydata.append([0.945, 318.2])

# calculating the mean and standard deviation using numpy
mean=np.mean(xdata, axis=0)
std=np.std(xdata, axis=0)
print('mean:', mean)
print('standard deviation:', std)
#standardize the data
Nx = []
for i in range(len(xdata)):
    Nx.append([ (xdata[i][0]/mean[0]) , (xdata[i][1]/mean[1]) , (xdata[i][2]/mean[2])])
xdata = Nx

xarray= np.array(xdata)
yarray= np.array(ydata)
print('Normalized input data:\n', xarray)
print('output data:\n', yarray)
%store mean
%store std


xarray= numpy.array(xdata)
yarray= numpy.array(ydata)
print (xdata)
print (xarray)
print (ydata)
print (yarray)

mean: [1.05192308e-02 8.58653846e+02 9.64920577e-02]
standard deviation: [2.07077080e-03 1.97026246e+02 3.63777177e-02]
Normalized input data:
 [[0.76051188 0.64053751 0.6380836 ]
 [0.76051188 0.75699888 0.75332625]
 [0.76051188 0.87346025 0.87012343]
 [0.76051188 0.98992161 0.96868076]
 [0.76051188 1.10638298 1.10216325]
 [0.76051188 1.22284434 1.19398428]
 [0.76051188 1.33930571 1.33378853]
 [0.76051188 0.98992161 0.98619516]
 [0.76051188 0.64053751 0.45578881]
 [0.76051188 0.87346025 0.62150193]
 [0.76051188 1.10638298 0.78721505]
 [0.76051188 1.22284434 0.86463075]
 [0.76051188 1.33930571 0.95240999]
 [0.76051188 0.98992161 0.70441031]
 [0.76051188 0.64053751 0.35443332]
 [0.76051188 0.87346025 0.48335584]
 [0.76051188 1.10638298 0.61227837]
 [0.76051188 1.33930571 0.74099363]
 [0.76051188 0.98992161 0.54781711]
 [1.04570384 0.64053751 0.8767561 ]
 [1.04570384 0.87346025 1.19595335]
 [1.04570384 1.10638298 1.51515061]
 [1.04570384 1.33930571 1.83434786]
 [1.04570384 0.98992161 1.35

### Task 1.1b

In [4]:
from sklearn.model_selection import train_test_split
train_xarray,valid_xarray,train_yarray,valid_yarray = train_test_split(xarray, yarray, test_size=0.25, random_state=13)

print('training input array:')
print(train_xarray)
print('validation input array:') 
print(valid_xarray)
print('training output array:')
print(train_yarray)
print('validation output array:') 
print(valid_yarray)

training input array:
[[0.76051188 1.33930571 0.74099363]
 [0.76051188 0.87346025 0.48335584]
 [1.04570384 0.87346025 0.66461429]
 [1.23583181 1.33930571 2.16805409]
 [0.76051188 1.22284434 1.19398428]
 [0.76051188 0.98992161 0.96868076]
 [0.76051188 0.98992161 0.98619516]
 [1.23583181 1.10638298 1.27927627]
 [0.76051188 1.33930571 0.95240999]
 [0.76051188 0.64053751 0.45578881]
 [1.04570384 1.22284434 1.17522626]
 [1.04570384 0.64053751 0.6266837 ]
 [1.23583181 0.98992161 0.89022871]
 [0.76051188 0.75699888 0.75332625]
 [1.04570384 0.64053751 0.48708672]
 [1.23583181 0.98992161 1.14465379]
 [1.04570384 1.33930571 1.83434786]
 [1.23583181 0.64053751 1.0368729 ]
 [1.04570384 1.33930571 1.01915124]
 [1.04570384 1.10638298 1.51515061]
 [1.04570384 0.64053751 0.8767561 ]
 [1.04570384 1.10638298 0.84193458]
 [1.23583181 0.64053751 0.74068272]
 [0.76051188 1.22284434 0.86463075]
 [0.76051188 0.87346025 0.62150193]
 [1.23583181 1.10638298 0.99500417]
 [0.76051188 0.98992161 0.70441031]
 [1.23

In [ ]:
'''>>>>> start CodeP4.1F22
    V.P. Carey ME249, Fall 2022

Keras Neural Network Modeling '''

#import useful packages
import keras
import pandas as pd
from keras.models import Sequential
import numpy as np
import keras.backend as kb
import tensorflow as tf
#the following 2 lines are only needed for Mac OS machines
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

# define meadian values of input variables - add your values here
Tamed = 1.  #make sure Tamed does not = 0
IDmed = 1.
RLmed = 1.

#create input data array
xdata = []

#Part 1 input data: Air temp (degC), ID (W/sqm), load resistance (ohms)
xdata = [[-10.0, 350, 4.464]] 
xdata.append([-10.0, 650, 4.464]) 
xdata.append([-10.0, 950, 4.464]) 
xdata.append([-10.0, 1250, 4.464])
''' ADD THE REST OF THE INPUT DATA AND CONVERT TO:
xdata = [[-10.0/Tamed, 350/IDmed, 4.464/RLmed]] 
xdata.append([-10.0/Tamed, 650/IDmed, 4.464/RLmed]) 
xdata.append([-10.0/Tamed, 950/IDmed, 4.464/RLmed]) 
xdata.append([-10.0/Tamed, 1250/IDmed, 4.464/RLmed]) 
... etc.'''

xarray= np.array(xdata)
print (xdata)
print (xarray)

# define meadian values of input variables - add your values here
VLmed = 1.
Wdmed = 1

#create input data array
ydata = []

#Part 1 output data: VL (V) and Power out Wd (W)
ydata = [[18.9, 80.3]] 
ydata.append([23.5, 124.6]) 
ydata.append([24.8, 138.6]) 
ydata.append([25.6, 146.9]) 
''' ADD THE REST OF THE OUPUT DATA AND CONVERT TO:
ydata = [[18.9/VLmed, 80.3/Wdmed]] 
ydata.append([23.5/VLmed, 124.6/Wdmed]) 
ydata.append([24.8/VLmed, 138.6/Wdmed]) 
ydata.append([25.6/VLmed, 146.9/Wdmed]) 
... etc.'''

yarray= np.array(ydata)
print (ydata)
print (yarray)

In [ ]:
# define neural network model

#As seen below, we have created four dense layers. 
#A dense layer is a layer in neural network that’s fully connected. 
#In other words, all the neurons in one layer are connected to all other neurons in the next layer.
#In the first layer, we need to provide the input shape, which is 1 in our case. 
#The activation function we have chosen is elu, which stands for exponential linear unit. .

from keras import backend as K
#initialize weights with values between -0.2 and 0.5
initializer = keras.initializers.RandomUniform(minval= -0.2, maxval=0.5)

model = keras.Sequential([
    keras.layers.Dense(6, activation=K.elu, input_shape=[3],  kernel_initializer=initializer),
    keras.layers.Dense(8, activation=K.elu,  kernel_initializer=initializer),
    keras.layers.Dense(16, activation=K.elu,  kernel_initializer=initializer),
    keras.layers.Dense(8, activation=K.elu, kernel_initializer=initializer),
    keras.layers.Dense(2,  kernel_initializer=initializer)
  ])


In [ ]:
#We’re using RMSprop as our optimizer here. RMSprop stands for Root Mean Square Propagation. 
#It’s one of the most popular gradient descent optimization algorithms for deep learning networks. 
#RMSprop is an optimizer that’s reliable and fast.
#We’re compiling the mode using the model.compile function. The loss function used here 
#is mean squared error. After the compilation of the model, we’ll use the fit method with ~500 epochs.
#Number of epochs can be varied.

#from tf.keras import optimizers
rms = keras.optimizers.RMSprop(0.020)
model.compile(loss='mean_absolute_error',optimizer=rms)


In [ ]:
#After the compilation of the model, we’ll use the fit method with 500 epochs.
#I started with epochs value of 100 and then tested the model after training. 
#The prediction was not that good. Then I modified the number of epochs to 200 and tested the model again. 
#Accuracy had improved slightly, but figured I’d give it one more try. Finally, at 500 epochs 
#I found acceptable prediction accuracy.

#The fit method takes three parameters; namely, x, y, and number of epochs. 
#During model training, if all the batches of data are seen by the model once, 
#we say that one epoch has been completed.

# Add an early stopping callback
es = keras.callbacks.EarlyStopping(
    monitor='loss', 
    mode='min', 
    patience = 80, 
    restore_best_weights = True, 
    verbose=1)
# Add a checkpoint where loss is minimum, and save that model
mc = keras.callbacks.ModelCheckpoint('best_model.SB', monitor='loss', 
                     mode='min',  verbose=1, save_best_only=True)

historyData = model.fit(xarray,yarray,epochs=800,callbacks=[es])

loss_hist = historyData.history['loss']
#The above line will return a dictionary, access it's info like this:
best_epoch = np.argmin(historyData.history['loss']) + 1
print ('best epoch = ', best_epoch)
print('smallest loss =', np.min(loss_hist))

model.save('./best_model')

In [ ]:


# This line of code can be used to reconstruct the saved model.

recon_model = keras.models.load_model("best_model")

# the name of the model is now "recon_model". You can then use this model to do predictions for comparisons.
# See the previous project for code to do the comparisons.






